modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="All Rights Reserved" #mandatory
issueTrackerURL="https://github.com/muttnes/MuttnesFlashlightMod/issues" #optional
[[mods]] #mandatory
modId="muttnesflashlight" #mandatory
version="2.0.0" #mandatory
displayName="Muttnes's Flashlight" #mandatory
logoFile="mod_thumb.png"
authors="Muttnes"
description='''Simple mod that adds a flashlight to the game'''
[[dependencies.muttnesflashlight]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the dependency is not mandatory
    # BEFORE - This mod is loaded BEFORE the dependency
    # AFTER - This mod is loaded AFTER the dependency
    ordering="NONE"
    side="BOTH"

[[dependencies.muttnesflashlight]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.muttnesflashlight]]
    modId="dynamiclights"
    mandatory=true
    versionRange="[1.20.1.2,]"
    ordering="NONE"
    side="CLIENT"